"""
Dashboard Generator (Visualization Agent)
------------------------------------------
Reads data/insights.json (produced by the Analysis Agent) and:
1. Generates 3 charts using matplotlib, saved as PNGs in assets/
2. Builds a static dashboard.html page displaying the key numbers + charts
"""

import json
import matplotlib
matplotlib.use("Agg")  # no GUI needed, just save images
import matplotlib.pyplot as plt

with open("data/insights.json") as f:
    insights = json.load(f)

# ---- Chart 1: Sales by Region (bar) ----
plt.figure(figsize=(6, 4))
regions = list(insights["sales_by_region"].keys())
values = list(insights["sales_by_region"].values())
plt.bar(regions, values, color="#4fd1c5")
plt.title("Sales by Region")
plt.ylabel("Sales ($)")
plt.tight_layout()
plt.savefig("assets/chart_region.png")
plt.close()

# ---- Chart 2: Sales by Category (pie) ----
plt.figure(figsize=(6, 4))
categories = list(insights["sales_by_category"].keys())
cat_values = list(insights["sales_by_category"].values())
plt.pie(cat_values, labels=categories, autopct="%1.0f%%", colors=["#4fd1c5", "#f2a65a", "#7f8fa6"])
plt.title("Sales by Category")
plt.tight_layout()
plt.savefig("assets/chart_category.png")
plt.close()

# ---- Chart 3: Top 5 Products (horizontal bar) ----
plt.figure(figsize=(6, 4))
products = list(insights["top_5_products"].keys())
prod_values = list(insights["top_5_products"].values())
plt.barh(products, prod_values, color="#f2a65a")
plt.title("Top 5 Products by Sales")
plt.xlabel("Sales ($)")
plt.tight_layout()
plt.savefig("assets/chart_top_products.png")
plt.close()

print("[Dashboard] Saved 3 charts to assets/")

# ---- Build the HTML dashboard ----
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Retail Data Pipeline — Dashboard</title>
<style>
  body {{ background: #0f1420; color: #e7e6e1; font-family: Arial, sans-serif; padding: 2rem; }}
  h1 {{ font-size: 1.8rem; }}
  .stats {{ display: flex; gap: 1.5rem; flex-wrap: wrap; margin: 1.5rem 0 2rem; }}
  .stat {{ background: #161c2b; border: 1px solid #2b3348; border-radius: 8px; padding: 1rem 1.5rem; }}
  .stat .num {{ font-size: 1.6rem; color: #4fd1c5; font-weight: bold; }}
  .stat .label {{ color: #97a0b5; font-size: 0.85rem; }}
  .charts {{ display: flex; gap: 1.5rem; flex-wrap: wrap; }}
  .charts img {{ background: white; border-radius: 8px; max-width: 420px; width: 100%; }}
</style>
</head>
<body>
  <h1>Retail Data Pipeline — Results</h1>
  <p>Generated by the multi-agent pipeline: Orchestrator → Clean Agent → Analysis Agent → Dashboard</p>

  <div class="stats">
    <div class="stat"><div class="num">${insights['total_sales']:,.2f}</div><div class="label">Total Sales</div></div>
    <div class="stat"><div class="num">${insights['total_profit']:,.2f}</div><div class="label">Total Profit</div></div>
    <div class="stat"><div class="num">{insights['total_orders']}</div><div class="label">Total Orders</div></div>
    <div class="stat"><div class="num">{insights['total_quantity']}</div><div class="label">Units Sold</div></div>
  </div>

  <div class="charts">
    <img src="chart_region.png" alt="Sales by Region">
    <img src="chart_category.png" alt="Sales by Category">
    <img src="chart_top_products.png" alt="Top 5 Products">
  </div>
</body>
</html>
"""

with open("assets/dashboard.html", "w", encoding="utf-8") as f:
    f.write(html)

print("[Dashboard] Saved dashboard to assets/dashboard.html")
